name: deploy docs

on:
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  test:
    name: Deploy docs
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: xdebug
          tools: composer:v2

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: PHP Version Check
        run: php -v

      - name: Validate Composer JSON
        run: composer validate

      - name: Run Composer
        run: composer install --no-interaction

      - name: Generate Docs
        run: |
          composer phpdoc

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: phpdoc
          folder: phpdoc
